//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        public int Id { get; set; }
        public int ModuleId { get; set; }
        public int ActivityTypeId { get; set; }
        public int TotalHours { get; set; }
        public int EvalTypeId { get; set; }
        public int RoomTypeId { get; set; }
        public int StaffId { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string ModifiedBy { get; set; }
        public string GroupNumber { get; set; }
    
        public virtual ActivityType ActivityType { get; set; }
        public virtual EvalType EvalType { get; set; }
        public virtual Module Module { get; set; }
        public virtual RoomType RoomType { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
