//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Module
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Module()
        {
            this.Activities = new HashSet<Activity>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string NameEN { get; set; }
        public string ModuleCode { get; set; }
        public int DepartmentId { get; set; }
        public string Specialization { get; set; }
        public int Coordinator { get; set; }
        public int PreparedYearId { get; set; }
        public int AcademicYearId { get; set; }
        public int SemesterId { get; set; }
        public int CourseTypeId { get; set; }
        public int DegreeTypeId { get; set; }
        public int StudyTypeId { get; set; }
        public int LanguageId { get; set; }
        public int ECTS { get; set; }
        public bool IsFL { get; set; }
        public string Note { get; set; }
        public bool IsActive { get; set; }
        public bool IsCompleted { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string ModifiedBy { get; set; }
        public int ModuleSize { get; set; }
        public int StatusId { get; set; }
        public int CoordinatorDeptId { get; set; }
    
        public virtual AcademicYear AcademicYear { get; set; }
        public virtual AcademicYear PreparedYear { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Activity> Activities { get; set; }
        public virtual CourseType CourseType { get; set; }
        public virtual DegreeType DegreeType { get; set; }
        public virtual Department Department { get; set; }
        public virtual Department Department1 { get; set; }
        public virtual Language Language { get; set; }
        public virtual ModuleStatusSet ModuleStatusSet { get; set; }
        public virtual Semester Semester { get; set; }
        public virtual Staff Staff { get; set; }
        public virtual StudyType StudyType { get; set; }
    }
}
