//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModuleList
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string NameEN { get; set; }
        public string ModuleCode { get; set; }
        public string Department { get; set; }
        public string Specialization { get; set; }
        public string Coordinator { get; set; }
        public string AcademicYear { get; set; }
        public int Semester { get; set; }
        public string CourseType { get; set; }
        public string DegreeType { get; set; }
        public string StudyType { get; set; }
        public string Language { get; set; }
        public int ECTS { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string ModifiedBy { get; set; }
    }
}
