//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UPOSEntities : DbContext
    {
        public UPOSEntities()
            : base("name=UPOSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AcademicYear> AcademicYears { get; set; }
        public virtual DbSet<Activity> Activities { get; set; }
        public virtual DbSet<ActivityType> ActivityTypes { get; set; }
        public virtual DbSet<AppLookup> AppLookups { get; set; }
        public virtual DbSet<AvailabilityPeriod> AvailabilityPeriods { get; set; }
        public virtual DbSet<CourseType> CourseTypes { get; set; }
        public virtual DbSet<CurrentSemester> CurrentSemesters { get; set; }
        public virtual DbSet<DegreeType> DegreeTypes { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<EvalType> EvalTypes { get; set; }
        public virtual DbSet<Language> Languages { get; set; }
        public virtual DbSet<Module> Modules { get; set; }
        public virtual DbSet<ModuleStatusSet> ModuleStatusSets { get; set; }
        public virtual DbSet<RoomType> RoomTypes { get; set; }
        public virtual DbSet<Semester> Semesters { get; set; }
        public virtual DbSet<StaffAvailability> StaffAvailabilities { get; set; }
        public virtual DbSet<Staff> Staffs { get; set; }
        public virtual DbSet<StudyType> StudyTypes { get; set; }
        public virtual DbSet<TimeInterval> TimeIntervals { get; set; }
        public virtual DbSet<Title> Titles { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<ActivityList> ActivityLists { get; set; }
        public virtual DbSet<ModuleList> ModuleLists { get; set; }
        public virtual DbSet<vwRoomAvailability> vwRoomAvailabilities { get; set; }
    }
}
